<?php
/**
 * Created by PhpStorm.
 * User: Николай
 * Date: 18.11.2018
 * Time: 20:06
 */

namespace app\models\search;

use yii\base\Model;

class SiteSearchForm extends Model
{
    public $q;

    public function rules()
    {
        return parent::rules(); // TODO: Change the autogenerated stub
        return[
            ['q','string'],
        ];
    }
}