<?php
/**
 * Created by PhpStorm.
 * User: Николай
 * Date: 18.11.2018
 * Time: 19:55
 */

namespace app\components;


use yii\base\Widget;

class SiteSearchWidget extends Widget
{
    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub
        $form=new SiteSearchForm();
        $this->render('siteSearch',array('form'=>$form));
    }

}