<?php
/**
 * Created by PhpStorm.
 * User: Николай
 * Date: 17.11.2018
 * Time: 15:20
 */

namespace app\components\taskList;


use Yii;
use yii\base\InvalidConfigException;
use yii\base\Widget;
use yii\helpers\Html;
use  yii\helpers\Url;
use yii\web\View;


class TaskWidget extends Widget
{

    public $query;
    public $headerText;
    public $url;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
      /*  if($this->query===null){
            throw new InvalidConfigException('Надо установить свойство запроса');
        }*/
        if($this->headerText===null){
            $this->headerText="Заголовок по умолчанию";
        }
    }
    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub
        $this->registerAssets();//Выносим регистрацию стилей в отдельный метод

      // if($this->query->count()>0){

            $header=$this->headerText;
            $query=$this->query;

        return $this->render('index',compact('header','query'));//Html::encode($this->url);
        }
       //return'';
       // }

    protected function registerAssets()
    {
        $view=$this->getView();//Получаем объект вида, в котором рендерится виджет
        TaskAssets::register($view);//Регистрируем файл с классом наборов css, js
    }
}