<?php
/**
 * Created by PhpStorm.
 * User: Николай
 * Date: 17.08.2018
 * Time: 16:31
 */

namespace app\models;
use yii\behaviors\TimestampBehavior;
use  yii\db\Expression;
use yii\db\ActiveRecord;

class TestForm2 extends ActiveRecord
{
    public static function tableName()
    {
        //public $createdAt='created_at';
        return 'teacher';
    }
    /* public function behaviors()
   {
       return[
           TimestampBehavior::className(),

       ];
   }*/
    /* public function behaviors()
     {
         //return parent::behaviors(); // TODO: Change the autogenerated stub

         return[
             [
                 'class'=>TimestampBehavior::className(),
                 'attributes'=>[
                     \yii\db\BaseActiveRecord::EVENT_BEFORE_INSERT=>['created_at'],
                     \yii\db\BaseActiveRecord::EVENT_BEFORE_UPDATE=>false,
                 ],
                 'value'=>function(){return date('U');},//gmdate("Y-m-d H:i:s"); }
               // new\yii\db\Expression('NOW()'),
             ],
         ];
     }*/

    public function  attributeLabels()
    {
        return [
            'name'=>'Имя',
            'email'=>'E-mail',
            'text'=>'Текст сообщения',
            //'created_at'=>'Создание',
            //'updated_at'=>'Изменение'
        ];
    }
    public  function rules()
    {
        return [
            [['name','text'],'required'],
            ['email','email'],

        ];
    }

   }